twig:
    exception_controller: null # This is needed to fix the deprecation in Symfony 4.4
    default_path: '%kernel.project_dir%/templates'
    debug: true
    strict_variables: true
    form_themes: ['bootstrap_4_layout.html.twig', '/form/recaptcha3.html.twig']
    paths:
        '%kernel.project_dir%/templates/email': email
