monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
        nested:
            type: stream
            path: "php://stderr"
            level: debug
# monolog:
#     handlers:
#         main:
#             type:         fingers_crossed
#             # 500 errors are logged at the critical level
#             action_level: critical
#             # to also log 400 level errors (but not 404's):
#             # action_level: error
#             # excluded_404s:
#             #     - ^/
#             handler:      deduplicated
#         deduplicated:
#             type:    deduplication
#             handler: symfony_mailer
#         symfony_mailer:
#             type: service
#             id: monolog_mailer_handler

